/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProposeRouteImport } from './routes/_app.propose'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppForgeRouteImport } from './routes/_app.forge'
import { Route as AppDominanceRouteImport } from './routes/_app.dominance'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppAgentsIndexRouteImport } from './routes/_app.agents.index'
import { Route as AppProposalsSlugRouteImport } from './routes/_app.proposals.$slug'
import { Route as AppMemorySlugRouteImport } from './routes/_app.memory.$slug'
import { Route as AppAgentsSlugRouteImport } from './routes/_app.agents.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProposeRoute = AppProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppForgeRoute = AppForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AppRoute,
} as any)
const AppDominanceRoute = AppDominanceRouteImport.update({
  id: '/dominance',
  path: '/dominance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppProposalsSlugRoute = AppProposalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppMemorySlugRoute = AppMemorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppAgentsSlugRoute = AppAgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/dominance': typeof AppDominanceRoute
  '/forge': typeof AppForgeRoute
  '/memory': typeof AppMemoryRouteWithChildren
  '/proposals': typeof AppProposalsRouteWithChildren
  '/propose': typeof AppProposeRoute
  '/agents/$slug': typeof AppAgentsSlugRoute
  '/memory/$slug': typeof AppMemorySlugRoute
  '/proposals/$slug': typeof AppProposalsSlugRoute
  '/agents/': typeof AppAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/dominance': typeof AppDominanceRoute
  '/forge': typeof AppForgeRoute
  '/memory': typeof AppMemoryRouteWithChildren
  '/proposals': typeof AppProposalsRouteWithChildren
  '/propose': typeof AppProposeRoute
  '/': typeof AppIndexRoute
  '/agents/$slug': typeof AppAgentsSlugRoute
  '/memory/$slug': typeof AppMemorySlugRoute
  '/proposals/$slug': typeof AppProposalsSlugRoute
  '/agents': typeof AppAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dominance': typeof AppDominanceRoute
  '/_app/forge': typeof AppForgeRoute
  '/_app/memory': typeof AppMemoryRouteWithChildren
  '/_app/proposals': typeof AppProposalsRouteWithChildren
  '/_app/propose': typeof AppProposeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$slug': typeof AppAgentsSlugRoute
  '/_app/memory/$slug': typeof AppMemorySlugRoute
  '/_app/proposals/$slug': typeof AppProposalsSlugRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/dominance'
    | '/forge'
    | '/memory'
    | '/proposals'
    | '/propose'
    | '/agents/$slug'
    | '/memory/$slug'
    | '/proposals/$slug'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/dominance'
    | '/forge'
    | '/memory'
    | '/proposals'
    | '/propose'
    | '/'
    | '/agents/$slug'
    | '/memory/$slug'
    | '/proposals/$slug'
    | '/agents'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agents'
    | '/_app/analytics'
    | '/_app/dominance'
    | '/_app/forge'
    | '/_app/memory'
    | '/_app/proposals'
    | '/_app/propose'
    | '/_app/'
    | '/_app/agents/$slug'
    | '/_app/memory/$slug'
    | '/_app/proposals/$slug'
    | '/_app/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propose': {
      id: '/_app/propose'
      path: '/propose'
      fullPath: '/propose'
      preLoaderRoute: typeof AppProposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forge': {
      id: '/_app/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AppForgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dominance': {
      id: '/_app/dominance'
      path: '/dominance'
      fullPath: '/dominance'
      preLoaderRoute: typeof AppDominanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/proposals/$slug': {
      id: '/_app/proposals/$slug'
      path: '/$slug'
      fullPath: '/proposals/$slug'
      preLoaderRoute: typeof AppProposalsSlugRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/_app/memory/$slug': {
      id: '/_app/memory/$slug'
      path: '/$slug'
      fullPath: '/memory/$slug'
      preLoaderRoute: typeof AppMemorySlugRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/agents/$slug': {
      id: '/_app/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AppAgentsSlugRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsSlugRoute: typeof AppAgentsSlugRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsSlugRoute: AppAgentsSlugRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppMemoryRouteChildren {
  AppMemorySlugRoute: typeof AppMemorySlugRoute
}

const AppMemoryRouteChildren: AppMemoryRouteChildren = {
  AppMemorySlugRoute: AppMemorySlugRoute,
}

const AppMemoryRouteWithChildren = AppMemoryRoute._addFileChildren(
  AppMemoryRouteChildren,
)

interface AppProposalsRouteChildren {
  AppProposalsSlugRoute: typeof AppProposalsSlugRoute
}

const AppProposalsRouteChildren: AppProposalsRouteChildren = {
  AppProposalsSlugRoute: AppProposalsSlugRoute,
}

const AppProposalsRouteWithChildren = AppProposalsRoute._addFileChildren(
  AppProposalsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDominanceRoute: typeof AppDominanceRoute
  AppForgeRoute: typeof AppForgeRoute
  AppMemoryRoute: typeof AppMemoryRouteWithChildren
  AppProposalsRoute: typeof AppProposalsRouteWithChildren
  AppProposeRoute: typeof AppProposeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDominanceRoute: AppDominanceRoute,
  AppForgeRoute: AppForgeRoute,
  AppMemoryRoute: AppMemoryRouteWithChildren,
  AppProposalsRoute: AppProposalsRouteWithChildren,
  AppProposeRoute: AppProposeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
